### ISSUE TITLE
pyplotter will not launch due to use of obsolete SciPy command

### ISSUE THREAD

**Issue by nfortune** [pyplotter/pyplotter#12]
when attempting to launch, I get the following error: 
_ImportError: cannot import name 'cumtrapz' from 'scipy.integrate'_ 

This is because cumtrapz is a long deprecated command that has now been removed in favor of cumulative_trapezoid

**From SciPy 1.1.14.0 release notes** 

"There is an ongoing effort to follow through on long-standing deprecations. The following previously deprecated features are affected in SciPy 1.14

...
scipy.integrate.{simps,trapz,cumtrapz} have been removed in favour of simpson, trapezoid, and cumulative_trapezoid"

**Comment by edumur** [comment]
Thanks for the detailed report.
I just pushed a quick fixed.
Please try it out and tell me if it works for you.

**Comment by nfortune** [comment]
project now successfully installs and launches. Thanks!
