### ISSUE TITLE
Liveplot with 2D dataset

### ISSUE THREAD

**Issue by Quantfoam** [pyplotter/pyplotter#4]
Hello,

I am trying to use Pyplotter to look at the output of a VNA as function of a voltage applied on a coil. So I would like to see live the result appearing slice by slice each time there is a new trace that was acquired. I can visualize very well the data when I click on the corresponding run_id but the live plotter does not work. Am I doing something wrong or live plotting is not implemented for 2D plots yet?

I tried to write a short code to simulate a bit the way I acquire the data

```

import numpy as np
import qcodes as qc
import time
from qcodes import initialise_database
from qcodes.dataset.experiment_container import new_experiment
from qcodes.dataset.measurements import Measurement

# Define the parameters for the simulated data
voltage_range = np.linspace(0, 10, 100)  # Voltage range from 0 to 10V
frequency_range = np.linspace(1e9, 10e9, 100)  # Frequency range from 1 GHz to 10 GHz

# Function to simulate random dB values
def simulate_dB_values():
    min_dB = -30  # Minimum dB value
    max_dB = 10   # Maximum dB value
    return np.random.uniform(min_dB, max_dB)

# Initialize a new QCoDeS database
db_path = './VNA_measurement.db'
initialise_database()
qc.config["core"]["db_location"] = db_path

# Create a new experiment
exp = new_experiment(name='VNA_measurement', sample_name='no_sample')

# Start a new measurement
meas = Measurement(exp=exp)
meas.register_custom_parameter('Frequency', unit='Hz')
meas.register_custom_parameter('Voltage', unit='V')
meas.register_custom_parameter('dB', unit='dB', setpoints=('Frequency', 'Voltage'))

# Populate the database with the simulated data
with meas.run() as datasaver:
    for f in frequency_range:
        for v in voltage_range:
            db_value = simulate_dB_values()  # Get a random dB value
            datasaver.add_result(('Frequency', f), ('Voltage', v), ('dB', db_value))
        time.sleep(1)  # Wait for 1 second before moving to the next frequency value

    dataset = datasaver.dataset  # Save the dataset

# Displaying the dataset ID and location
dataset_id = dataset.run_id
print(f"Dataset ID: {dataset_id}")
print(f"Database location: {db_path}")

```

**Comment by Quantfoam** [comment]
Anyone has any idea?

Also after swapping axes on a color plot and then taking a slice the units are not swapped.

**Comment by edumur** [comment]
Hi,

I missed your first message as I was in vacation ^^'...
I will have a look on the error now.

**Comment by edumur** [comment]
Hi,

I just pushed something to solve your issue.
Can you test and give me some feedback?

**Comment by Quantfoam** [comment]
Hi!

Thanks a lot! So the liveplotting now works which is amazing. On the other end I would like to understand why my data does not have labels. 
Is it not defined automatically when I do **meas.register_custom_parameter('Frequency', unit='Hz')** ?

Also if I do swap axis and then a slice the unit showed is Hz and not V (but the curve looks great). 

Is there a better way to save the data so it would be understood better by Pyplotter?

Thanks a lot again!

**Comment by edumur** [comment]
Hi,

if you look at the parameter function you're using:
```python
def register_custom_parameter(
    name: str,
    label: str | None = None,
    unit: str | None = None,
    basis: setpoints_type | None = None,
    setpoints: setpoints_type | None = None,
    paramtype: str = "numeric"
) -> Measurement
```

So when you do `meas.register_custom_parameter('Frequency', unit='Hz')`, you only define `name` and `unit`.
To define a label as well you could do something like" `meas.register_custom_parameter('Frequency', 'Frequency', unit='Hz')`.

**Comment by edumur** [comment]
I tried to solve the bug of slicing and labels.
Could you check and give feedback?


I think the way you save your data is correct ;) .

**Comment by Quantfoam** [comment]
Works perfectly thanks!

I just noticed right now that if I click on draw isocurve and then remove them the isocurves stay on the graph. 

Also what would be the best solution if I want to plot live a few curves. For example a simple graph like that:
https://i.stack.imgur.com/1NHzt.png

The best would be to create additional plots in the same fashion the data slicing is working or is it possible to directly build a "complex" plot like that?

Thanks again!

**Comment by edumur** [comment]
Hi,

Thanks for the report, the isocurve issue should be solve.
Please try and give feedback.

Concerning the matplotlib figure you shown, you would have to make it yourself.
Such graph are out of the scope of the pyplotter project.
To do it, download the data on a notebook via `load_by_id` and so one qcodes function and then follow the matplotlib tutorial.

**Comment by Quantfoam** [comment]
Hi thanks a lot,

The isocurve is working. Actually about my previous comment the only I think would be beneficial would be to have the option to have the graphs tiled on the screen and not appear on top of each other so each time I am starting an experiment that shows 4 graphs they appear on top of each other and I need to move them manually. I can also try to live with that :)

**Comment by edumur** [comment]
I added sometiling features.
Could you try and give a feedback?

Thanks.

**Comment by Quantfoam** [comment]
Looks great!

**Comment by edumur** [comment]
Perfect!
I will close your issue then.
