### ISSUE TITLE
Impossible to read s2p files

### ISSUE THREAD

**Issue by Quantfoam** [pyplotter/pyplotter#5]
Hi,

1. I can't put my finger on why but the s2p files in pyplotter are not recognized in most of the computers I have. It is nevertheless working on one of the computer so I put you the versions of the packages. on the computer where it works and where it does not. 
2. Also would it be possible to support reading .npz files. I think many people save data in this way so it could be a good idea(but I don't know how complicated it would be to implement)

Working with this setup:

`ansi2html==1.8.0
asteval==0.9.31
asttokens==2.2.1
attrs==23.1.0
azure-core==1.28.0
azure-identity==1.13.0
backcall==0.2.0
broadbean==0.11.0
cachetools==5.3.1
certifi==2023.7.22
cf-xarray==0.8.7
cffi==1.15.1
charset-normalizer==3.2.0
chart-studio==1.1.0
click==8.1.6
cloudpickle==2.2.1
colorama==0.4.6
comm==0.1.3
contextlib2==21.6.0
contourpy==1.1.0
cryptography==41.0.2
cycler==0.11.0
dash==2.11.1
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
dask==2023.7.1
debugpy==1.6.7
decorator==5.1.1
Deprecated==1.2.14
dill==0.3.7
executing==1.2.0
fastjsonschema==2.18.0
Flask==2.2.5
fonttools==4.41.1
fsspec==2023.6.0
future==0.18.3
google-api-core==2.11.1
google-auth==2.22.0
googleapis-common-protos==1.59.1
h5netcdf==1.2.0
h5py==3.9.0
idna==3.4
importlib-metadata==6.8.0
ipykernel==6.24.0
ipympl==0.9.3
ipython==8.14.0
ipython-genutils==0.2.0
ipywidgets==8.0.7
itsdangerous==2.1.2
jedi==0.18.2
Jinja2==3.1.2
jsonschema==4.18.4
jsonschema-specifications==2023.7.1
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyterlab-widgets==3.0.8
kiwisolver==1.4.4
lmfit==1.2.2
locket==1.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
matplotlib-inline==0.1.6
msal==1.23.0
msal-extensions==1.0.0
multiprocess==0.70.15
nbformat==5.9.1
nest-asyncio==1.5.6
numpy==1.25.1
opencensus==0.11.2
opencensus-context==0.1.3
opencensus-ext-azure==1.1.9
opentelemetry-api==1.22.0
packaging==23.1
pandas==2.0.3
parso==0.8.3
partd==1.4.0
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.9.1
plotly==5.15.0
plottr==0.13.0
portalocker==2.7.0
prompt-toolkit==3.0.39
protobuf==4.23.4
psutil==5.9.5
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.15.1
PyJWT==2.8.0
PyOpenGL==3.1.7
pyparsing==3.0.9
-e git+https://github.com/pyplotter/pyplotter@50ab0aeda0109c425f101f434cb742b2a7555d23#egg=pyplotter
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.12.2
PyQt6==6.5.2
PyQt6-Qt6==6.5.2
PyQt6-sip==13.5.2
pyqtgraph==0.13.3
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2
python-dateutil==2.8.2
pytz==2023.3
PyVISA==1.13.0
pywin32==306
PyYAML==6.0.1
pyzmq==25.1.0
qcodes==0.44.1
QDarkStyle==3.1
QtPy==2.3.1
rpds-py==0.9.2
rsa==4.9
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
schema==0.7.5
scikit-rf==0.28.0
scipy==1.11.1
seaborn==0.12.2
six==1.16.0
sqlitedict==2.1.0
stack-data==0.6.2
tabulate==0.9.0
tenacity==8.2.2
toolz==0.12.0
tornado==6.4
tqdm==4.65.0
traitlets==5.9.0
typing_extensions==4.7.1
tzdata==2023.3
uncertainties==3.1.7
urllib3==1.26.16
versioningit==2.2.0
watchdog==3.0.0
wcwidth==0.2.6
websockets==11.0.3
Werkzeug==2.2.3
widgetsnbextension==4.0.8
wrapt==1.15.0
xarray==2023.7.0
xhistogram==0.3.2
zipp==3.16.2`

Not working with this configuration:

`asteval==0.9.31
asttokens==2.4.1
attrs==23.2.0
azure-core==1.30.0
azure-identity==1.15.0
broadbean==0.13.0
cachetools==5.3.2
certifi==2024.2.2
cf_xarray==0.8.9
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
colorama==0.4.6
comm==0.2.1
contextlib2==21.6.0
contourpy==1.2.0
cryptography==42.0.2
cycler==0.12.1
dask==2024.2.0
debugpy==1.8.1
decorator==5.1.1
Deprecated==1.2.14
dill==0.3.8
executing==2.0.1
fonttools==4.48.1
fsspec==2024.2.0
future==0.18.3
google-api-core==2.17.0
google-auth==2.27.0
googleapis-common-protos==1.62.0
h5netcdf==1.3.0
h5py==3.10.0
idna==3.6
importlib-metadata==6.11.0
ipykernel==6.29.2
ipython==8.21.0
ipywidgets==8.1.2
jedi==0.19.1
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter_client==8.6.0
jupyter_core==5.7.1
jupyterlab_widgets==3.0.10
kiwisolver==1.4.5
lmfit==1.2.2
locket==1.0.0
matplotlib==3.8.2
matplotlib-inline==0.1.6
msal==1.26.0
msal-extensions==1.1.0
multiprocess==0.70.16
nest-asyncio==1.6.0
numpy==1.26.4
opencensus==0.11.4
opencensus-context==0.1.3
opencensus-ext-azure==1.1.13
opentelemetry-api==1.22.0
packaging==23.2
pandas==2.2.0
parso==0.8.3
partd==1.4.1
pillow==10.2.0
platformdirs==4.2.0
portalocker==2.8.2
prompt-toolkit==3.0.43
protobuf==4.25.2
psutil==5.9.8
pure-eval==0.2.2
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.17.2
PyJWT==2.8.0
PyOpenGL==3.1.7
pyparsing==3.1.1
-e git+https://github.com/pyplotter/pyplotter@50ab0aeda0109c425f101f434cb742b2a7555d23#egg=pyplotter
PyQt5==5.15.10
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
pyqtgraph==0.13.3
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2
python-dateutil==2.8.2
pytz==2024.1
PyVISA==1.14.1
pywin32==306
PyYAML==6.0.1
pyzmq==25.1.2
qcodes==0.44.1
QDarkStyle==3.2.3
QtPy==2.4.1
referencing==0.33.0
requests==2.31.0
rpds-py==0.17.1
rsa==4.9
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
schema==0.7.5
scikit-rf==0.31.0
scipy==1.12.0
six==1.16.0
stack-data==0.6.3
tabulate==0.9.0
toolz==0.12.1
tornado==6.4
tqdm==4.66.2
traitlets==5.14.1
typing_extensions==4.9.0
tzdata==2023.4
uncertainties==3.1.7
urllib3==2.2.0
versioningit==3.0.0
wcwidth==0.2.13
websockets==12.0
widgetsnbextension==4.0.10
wrapt==1.16.0
xarray==2024.1.1
zipp==3.17.0
`

Thanks again for this software, it is really nice!

**Comment by edumur** [comment]
Could you provide the python version as well on your 2 setups and an example of a s2p file?

Thanks.

**Comment by Quantfoam** [comment]
Hi so on the working one I have python 3.11.0
The version where it is not working is 3.12.0 (but I think it didn't work on 3.10.0 neither, I can check)

Find attached the s2p file
[testS2p.zip](https://github.com/pyplotter/pyplotter/files/14328538/testS2p.zip)

**Comment by edumur** [comment]
Could you pull and try reading s2p file now?

**Comment by Quantfoam** [comment]
It's working now thanks!

Any chance you would add support for npz files?
Also is it possible to show 1D plots without the line, like a scatter plot on matplotlib?

**Comment by edumur** [comment]
I can sure work on those two things.
Could you provide an example of a npz file?

Same thing about the lines you want to remove (need to be sure we are on the same page).

**Comment by Quantfoam** [comment]
For example here on the graph I have the lines connecting the datapoints and the symbols (cause I clicked on symbol)

![Capture](https://github.com/pyplotter/pyplotter/assets/140512609/e223e4b2-bfc9-456d-9803-0b5702ce3972)

I guess maybe the best would be to add a checkbox that would set pen=None in the pyqtgraph object (https://pyqtgraph.readthedocs.io/en/latest/getting_started/plotting.html)

Another goal would be to plot data in the same way as the central plot

:
![Capture2](https://github.com/pyplotter/pyplotter/assets/140512609/403d6999-5fc6-40a5-8e91-f88206432790)


About the npz file find attached one example (I had to zip it to uploaded it here) with the following attributes:
('time_array', 'probabilities', 'click_record', 'time_between_clicks', 'time_between_no_clicks') and for example being able to plot click_record vs. time_array

[click_record_data_15_02_2024__20_46_15.zip](https://github.com/pyplotter/pyplotter/files/14346109/click_record_data_15_02_2024__20_46_15.zip)

Last thing, is it possible to modify the number of digits of the mouse position on a color plot (x,y,z). Highlighted in red in the following picture:
![Capture3](https://github.com/pyplotter/pyplotter/assets/140512609/c172bf33-300d-4149-a4c8-72fccb3e06a3)

Thanks again.

**Comment by edumur** [comment]
Hi,

1. I added support to npz file, please give feedback.
2. you can change the display number decimal by tweeking the config file `"plotCoordinateNbNumber" : '2', # str, how many decimal for coordinates`,
3. The central plot goes beyond the scope of the plotter. I do not think it will be added anytime soon.
4. I can easily remove the line between the symbols.

Best.

**Comment by Quantfoam** [comment]
Thanks,

The npz file loading is working now. I think a nice feature would be to be able to plot one array versus another one. For example if I want to plot probabilities vs click record. Basically being able to plot one numpy array vs another one on the fly. It would also benefit for the csv file. 

Thanks for pointing the config file, I had a look and it looks like a very convenient way to tweak many parameters. 

Just to be sure we understand each other when I was talking about the central plot I was not referring to the two additional plots on the top and right of the picture. I was just talking about a basic scatter plot like this one:
![scatter](https://github.com/pyplotter/pyplotter/assets/140512609/661d8aa7-7e0e-4b15-a800-e74041fceb1b)

**Comment by edumur** [comment]
Hi,

I think you can already do what you are suggesting by loading the two arrays you want to plot, hide one and chose the x axis of the other. Like here:
![image](https://github.com/pyplotter/pyplotter/assets/13218882/f07272a8-2dde-4efb-b232-97485e290230)


Thanks, I misunderstood your suggestion!
I scatter plot is probably possible, I will check.

**Comment by Quantfoam** [comment]
Thanks a lot, I indeed didn't think about doing what you suggested. It is working great.

**Comment by edumur** [comment]
Hi,

You should be able to have scatter plot now.
Please give me a feedback.

**Comment by Quantfoam** [comment]
Works great. The only small downside is that when you add another curve, it adds the curve with different scatter symbol and not another color like for the lines. Sometimes it can be a bit hard to distinguish between the circles and the squares for example if you are zooming out.

**Comment by edumur** [comment]
Hi,

That's a good point!
I implemented this, what do you think?

![image](https://github.com/pyplotter/pyplotter/assets/13218882/e06285c7-750e-4f9a-a795-cb38a1941d76)

**Comment by Quantfoam** [comment]
Works very well, Thanks!
