### ISSUE TITLE
Support various database

### ISSUE THREAD

**Issue by xlelephant** [pyplotter/pyplotter#7]
Hello Etienne,

Thank you for sharing this repository!

I personally utilized labrad .datavault, developed by former students in the John Martinis Group, which saves each experimental dataset as an HDF5 file. Additionally, a Grapher.exe application is there for rapid figure rendering.
For now, I need to rewrite some functions to support this setup, such as:

workers.loadDataFromRun.getParameterInfo/getParameterDatamp
workers.loadNewData.LoadDataBaseThread
workers.loadRunInfo.getDependentSnapshotShapeFromRunId
ui.tableWidgetParameter.getData

I guess It would be great to have official support for such databases, such as .hdf5 files or MongoDB files. 
Alternatively, a general interface could be implemented to facilitate their integration as plugins.

**Comment by edumur** [comment]
Hi Xiang,

I used Labrad as well during my postdoc in Chicago so I know it well ;) .

The plotter support QCoDes database, csv, s2p, BlueFors log file and npz file.

Some information:
1. Loading the data works like this `tableWidgetParameter.getData`: here depending of the type of file the user click on, we launch different subRoutine.
For instance below we have a low support for csv file: only one qtSignal when the data are loaded, but heavy support for qcodes db file: it is done in a separete thread, we show a progress bar and so one.
```python
        if dataType=='qcodes':
            worker = LoadDataFromRunThread(curveId,
                                           databaseAbsPath,
                                           dependentParamName,
                                           plotRef,
                                           plotTitle,
                                           runId,
                                           windowTitle,
                                           cb,
                                           progressBarId)
            # Connect signals
            # To update the status bar
            worker.signal.sendStatusBarMessage.connect(self.signalSendStatusBarMessage)
            # To update the progress bar
            worker.signal.updateProgressBar.connect(self.signalUpdateProgressBar)
            # If data download failed
            worker.signal.loadedDataEmpty.connect(self.signalLoadedDataEmpty)
            # When data download is done
            worker.signal.loadedDataFull.connect(self.signalLoadedDataFull)

            # Execute the thread
            self.threadpool.start(worker)
        elif dataType=='csv':

            self.signalCSVLoadData.emit(curveId,
                                        databaseAbsPath,
                                        dependentParamName,
                                        plotRef,
                                        plotTitle,
                                        runId,
                                        windowTitle,
                                        cb,
                                        progressBarId)
```
The usual chain of QtSignal is the following, I will use the CSV as example: `tableWidgetParameter.getData`, `WidgetCSV.loadData`, `mainWindow.loadedDataFull`.
There is usually other QtSignals to handle progressBar.
The only requirement here is that your QtSignal chain ends towards the `mainWindow.loadedDataFull`.
2. A subtlety is that  qcodes database are opened in a Qt thread which, itself, opens the database in another python process. This was done to avoid a full crash of the software when opening qcodes database was causing such issue (I think it was a huge issue for people opening database through mounted network disk). The thread are located in the worker folder and the multiprocess functions in the `qcodesDatabase` file.
3. As the plotter is made for reading qcodes databse, you will have to "create" some run parameters such as "runId". I do this to read csv file for instance.
4. I would not make a plugin system as that seems out of my skill reached at the moment.
5. If you want to give it a go, I would start as follow: 
Add your filetype in the `config` file at the `authorizedExtension` key.
Then add your thread in the `TableWidgetParameter`
```python
        elif dataType=='labrad':
            worker = LoadLabradFromRunThread(...)
            # Connect signals
            # To update the status bar
            worker.signal.sendStatusBarMessage.connect(self.signalSendStatusBarMessage)
            # To update the progress bar
            worker.signal.updateProgressBar.connect(self.signalUpdateProgressBar)
            # If data download failed
            worker.signal.loadedDataEmpty.connect(self.signalLoadedDataEmpty)
            # When data download is done
            worker.signal.loadedDataFull.connect(self.signalLoadedDataFull)
```
Create a `LoadLabradFromRunThread` copying `LoadDataFromRunThread`. This will give you a good base to start I guess.

**Comment by tristanlorriaux** [comment]
Hi @xlelephant and @edumur !
We are also labRAD users there, and we would be happy to use this cool plotter with such a cool amount of features. But while we try to use the plotter, we can only enter a .dir folder and plot raw .csv (which is already amazing). But since the soft doesn't recognise our .dir as a database, we cannot access to live plotting, 2D plotting, etc. 
I think it comes from the way data are stored on our side, that is to say with a .csv and not a .hdf5 plus an associated .ini file. An example of a .ini could be:

```
[General]
created = 2026-05-20, 12:00:00
accessed = 2026-05-26, 17:00:20
modified = 2026-05-20, 12:00:00
title = Device measure
independent = 1
dependent = 2
parameters = 2
comments = 0

[Independent 1]
label = frequency
units = GHz

[Dependent 1]
label = log mag
units = dB
category = S21

[Dependent 2]
label = phase
units = rad
category = S21

[Parameter 1]
label = power
data = Value(0.0, 'dBm')

[Parameter 2]
label = bandwidth
data = Value(1.0, 'kHz')

[Comments]
```

And the .csv would be stored as: 

```
frequency1, mag1, phase1
frequency2, mag2, phase2
..
```

Do you see an easy code fix for our side, or do you think we could modify the way it detects labRAD databases? 
Great thanks in advance for the time you will spend on this ticket, and for sharing this incredible project 🚀

**Comment by edumur** [comment]
Hi @tristanlorriaux ,

I cannot help you too much here as @xlelephant is the one who added labrad support to the plotter.
Moreover it will be hard for you to help as I am not a labrad user.

I can however guide you a little bit by looking at @xlelephant's code.
if you look into `labradDatavault` file, you can see that most of the heavy change would have to happen here.
The method `_load` is the one opening the hdf5 file and translating it into something the plotter can handle.
You should start there.
